name = "app"
version = "1.0.0"
target = "javascript"

description = ""
licences = ["MIT"]
repository = { type = "github", user = "upsiflu", repo = "" }
links = [{ title = "Website", href = "https://flupsi.com" }]

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.0.2 and < 6.0.0"
rsvp = ">= 1.0.3 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.7.1 and < 2.0.0"
